//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from EventInterfaces
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

namespace UKnack.Events;

public interface ISubscriberToEvent 
{
    public void OnEventNotification();
    public string Description { get; }
}
