//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from EffortlessUpdaterFromValueSO
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UnityEngine;
using System.ComponentModel;
using UKnack.Attributes;
using UKnack.Values;
using UKnack.Preconcrete.UI.SimpleToolkit;

namespace UKnack.UI
{

    [AddComponentMenu("UKnack/UI.SimpleToolkit/EffortlessUpdaterFromValueSO/Vector2Int")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Browsable(false)]
    public sealed class EffortlessUpdaterFromValueSO_Vector2Int : EffortlessUpdaterFromValueSO<Vector2Int>
    {
        [SerializeField][ValidReference(nameof(ValidIValue))] private SOValue<Vector2Int> _value;

        protected override IValue<Vector2Int> GetValidValueProvider() 
            => ValidIValue(_value);

        protected override string RawValueToStringConversion(Vector2Int value)
            => value.ToString();
    

        public static IValue<Vector2Int> ValidIValue(UnityEngine.Object value)
        {
            if (value==null)
                throw new System.ArgumentNullException(nameof(value));
            var asIValue = value as IValue<Vector2Int>;
            if (asIValue == null)
                throw new System.InvalidCastException($"{value.GetType()} is not compatible with {typeof(IValue<Vector2Int>)}");
            return asIValue;
        }
    }
}

