//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from IValueGenerators
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Common;

namespace UKnack.Values;

public interface IValueSetterWithoutNotification<T>
{
    void SetValueWithoutNotify(T value);
}


