//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from IValueGenerators
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Common;

namespace UKnack.Values;

public interface IValueGetter<T>
{
    public T GetValue();

    public static IValueGetter<T> Validate(UnityEngine.Object obj) =>
        CommonStatic.ValidCast<IValueGetter<T>>(obj);
}


