//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from IValueGenerators
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Common;

namespace UKnack.Values;

public interface IValueSetter<T>
{
    public void SetValue(T value);

    public static IValueSetter<T> Validate(UnityEngine.Object obj) => 
        CommonStatic.ValidCast<IValueSetter<T>>(obj);

}


