//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_ValueSO
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UnityEngine;
using UKnack.Values;
using UKnack.Preconcrete.Values;

namespace UKnack.Concrete.Values
{

[CreateAssetMenu(fileName = "SOValue_float", menuName = "UKnack/SOValueMutable/float", order = 110)]
public sealed class SOValueMutable_Concrete_float : SOValueMutable<float>
    {
        [SerializeField] 
        private USetOrDefault<float> _value;

        public override float RawValue { get => _value.Value; protected set => _value.Value = value; }

        public float Increase()
        { 
            SetValue(GetValue() + 1); 
            return GetValue(); 
        }

    }

}
