//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_ValueSO
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UnityEngine;
using UKnack.Values;
using UKnack.Preconcrete.Values;

namespace UKnack.Concrete.Values
{

[CreateAssetMenu(fileName = "SOValue_int", menuName = "UKnack/SOValueMutable/int", order = 110)]
public sealed class SOValueMutable_Concrete_int : SOValueMutable<int>
    {
        [SerializeField] 
        private USetOrDefault<int> _value;

        public override int RawValue { get => _value.Value; protected set => _value.Value = value; }

        public int Increase()
        { 
            SetValue(GetValue() + 1); 
            return GetValue(); 
        }

    }

}
