//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_ValueSO
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UnityEngine;
using UKnack.Values;
using UKnack.Preconcrete.Values;

namespace UKnack.Concrete.Values
{

[CreateAssetMenu(fileName = "SOValue_bool", menuName = "UKnack/SOValueMutable/bool", order = 110)]
public sealed class SOValueMutable_Concrete_bool : SOValueMutable<bool>
    {
        [SerializeField] 
        private USetOrDefault<bool> _value;

        public override bool RawValue { get => _value.Value; protected set => _value.Value = value; }

    public void Flip() => ExtensionsForSOValues.Flip(this);

    }

}
