//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_ValueSO
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UnityEngine;
using UKnack.Values;
using UKnack.Preconcrete.Values;

namespace UKnack.Concrete.Values
{

[CreateAssetMenu(fileName = "SOValue_object", menuName = "UKnack/SOValueMutable/object", order = 110)]
public sealed class SOValueMutable_Concrete_object : SOValueMutable<object>
    {
        [SerializeField] 
        private USetOrDefault<object> _value;

        public override object RawValue { get => _value.Value; protected set => _value.Value = value; }


    }

}
