//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from CallbackContextDirectTo
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Attributes;
using UKnack.Events;
using UnityEngine;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Input
{
    [AddComponentMenu("UKnack/CallbackContext/To_IPublisher<Vector2>_DirectFrom_CallbackContext")]
    internal class CallbackContextDirectTo_IPublisher_Vector2 : MonoBehaviour, IPublisher<CallbackContext>
    {
        [SerializeField]
        [ValidReference(typeof(IPublisher<Vector2>), nameof(IPublisher<Vector2>.Validate), typeof(IPublisher<Vector2>))]
        [DisableEditingInPlaymode]
        private UnityEngine.Object _iPublisher;

        private IPublisher<Vector2> _iPublisherAsInterface;

        public void Publish(CallbackContext ctx)
        {
            Vector2 value = ctx.ReadValue<Vector2>();
            _iPublisherAsInterface.Publish(value);
        }

        private void Awake()
        {
            _iPublisherAsInterface = IPublisher<Vector2>.Validate(_iPublisher);
        }
    }
}
