//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from CallbackContextDirectTo
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Attributes;
using UKnack.Events;
using UnityEngine;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{
    [AddComponentMenu("UKnack/CallbackContextTo/CallbackContextDirectTo_IPublisher_float")]
    internal class CallbackContextDirectTo_IPublisher_float : MonoBehaviour, IPublisher<CallbackContext>
    {
        [SerializeField]
        [ValidReference(typeof(IPublisher<float>), nameof(IPublisher<float>.Validate), typeof(IPublisher<float>))]
        [DisableEditingInPlaymode]
        private UnityEngine.Object _iPublisher;

        private IPublisher<float> _iPublisherAsInterface;

        public void Publish(CallbackContext ctx)
        {
            float value = ctx.ReadValue<float>();
            _iPublisherAsInterface.Publish(value);
        }

        private void Awake()
        {
            _iPublisherAsInterface = IPublisher<float>.Validate(_iPublisher);
        }
    }
}
