//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from SOEventToUnityEventAdapter_FromGeneric
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Preconcrete.Commands;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{
    /// <summary>
    /// Subscribes UnityEvent to SOEvent. 
    /// </summary>
    [AddComponentMenu("UKnack/SOEventToUnityEventAdapters/SOEvent_Vector3_toUnityEvent")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEventToUnityEventAdapter_Concrete_Vector3 : AbstractCommandSubscribedToSOEvent<Vector3>
    {
        [SerializeField]
        [ValidReference(typeof(IEvent<Vector3>), nameof(IEvent<Vector3>.Validate))] 
        private SOEvent<Vector3> _subscribedTo;

        [SerializeField]
        private UnityEvent<Vector3> _unityEvent;

        protected override IEvent<Vector3> SubscribedTo => 
            IEvent<Vector3>.Validate(_subscribedTo);

        public override void Execute(Vector3 v) => 
            _unityEvent?.Invoke(v);

    }
}

