//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from SOEventToUnityEventAdapter_FromGeneric
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Preconcrete.Commands;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{
    /// <summary>
    /// Subscribes UnityEvent to SOEvent. 
    /// </summary>
    [AddComponentMenu("UKnack/SOEventToUnityEventAdapters/SOEvent_bool_toUnityEvent")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEventToUnityEventAdapter_Concrete_bool : AbstractCommandSubscribedToSOEvent<bool>
    {
        [SerializeField]
        [ValidReference(typeof(IEvent<bool>), nameof(IEvent<bool>.Validate))] 
        private SOEvent<bool> _subscribedTo;

        [SerializeField]
        protected UnityEvent<bool> _unityEvent;

        protected override IEvent<bool> SubscribedTo => 
            IEvent<bool>.Validate(_subscribedTo);

        public override void Execute(bool b) => 
            _unityEvent?.Invoke(b);

    }
}

