//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from SOEventToUnityEventAdapter_FromGeneric
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Preconcrete.Events;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{
    /// <summary>
    /// Subscribes UnityEvent to SOEvent. 
    /// </summary>
    [AddComponentMenu("UKnack/SOEventToUnityEventAdapters/SOEvent_CallbackContext_toUnityEvent")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEventToUnityEventAdapter_Concrete_CallbackContext : SOEventToUnityEventAdapter<CallbackContext>
    {
        [SerializeField]
        [ValidReference(typeof(IEvent<CallbackContext>), nameof(IEvent<CallbackContext>.Validate))] 
        private SOEvent<CallbackContext> _subscribedTo;

        protected override IEvent<CallbackContext> _iEvent => 
            IEvent<CallbackContext>.Validate(_subscribedTo);
    }
}

