//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from SOEventToUnityEventAdapter_FromGeneric
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Preconcrete.Commands;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{
    /// <summary>
    /// Subscribes UnityEvent to SOEvent. 
    /// </summary>
    [AddComponentMenu("UKnack/SOEventToUnityEventAdapters/SOEvent_nongeneric_toUnityEvent")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEventToUnityEventAdapter_Concrete_nongeneric : AbstractCommandSubscribedToSOEvent
    {
        [SerializeField]
        [ValidReference(typeof(IEvent), nameof(IEvent.Validate))] 
        private SOEvent _subscribedTo;

        [SerializeField]
        protected UnityEvent _unityEvent;

        protected override IEvent SubscribedTo => 
            IEvent.Validate(_subscribedTo);

        public override void Execute() => 
            _unityEvent?.Invoke();

    }
}

