//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from SOEventToUnityEventAdapter_FromGeneric
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Preconcrete.Commands;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{
    /// <summary>
    /// Subscribes UnityEvent to SOEvent. 
    /// </summary>
    [AddComponentMenu("UKnack/SOEventToUnityEventAdapters/SOEvent_string_string_toUnityEvent")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEventToUnityEventAdapter_Concrete_string_string : AbstractCommandSubscribedToSOEvent<string,string>
    {
        [SerializeField]
        [ValidReference(typeof(IEvent<string,string>), nameof(IEvent<string,string>.Validate))] 
        private SOEvent<string,string> _subscribedTo;

        [SerializeField]
        protected UnityEvent<string,string> _unityEvent;

        protected override IEvent<string,string> SubscribedTo => 
            IEvent<string,string>.Validate(_subscribedTo);

        public override void Execute(string s1,string s2) => 
            _unityEvent?.Invoke(s1,s2);

    }
}

