//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from SOEventToUnityEventAdapter_FromGeneric
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Preconcrete.Events;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{
    /// <summary>
    /// Subscribes UnityEvent to SOEvent. 
    /// </summary>
    [AddComponentMenu("UKnack/SOEventToUnityEventAdapters/SOEvent_Vector3_toUnityEvent")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEventToUnityEventAdapter_Concrete_Vector3 : SOEventToUnityEventAdapter<Vector3>
    {
        [SerializeField]
        [ValidReference(typeof(IEvent<Vector3>), nameof(IEvent<Vector3>.Validate))] 
        private SOEvent<Vector3> _subscribedTo;

        protected override IEvent<Vector3> _iEvent => 
            IEvent<Vector3>.Validate(_subscribedTo);
    }
}

