//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Events;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

    /// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
    [CreateAssetMenu(fileName = "SOEvent_string", menuName = "UKnack/SOEvents/SOEvent_string")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEvent_Concrete_string : SOEvent<string>
    {
        [SerializeField] private UnityEvent<string> _beforeSubscribers;
        [SerializeField] private UnityEvent<string> _afterSubscribers;

        internal override void InternalInvoke(string s)
        {
            _beforeSubscribers.Invoke(s);
            base.InternalInvoke(s);
            _afterSubscribers.Invoke(s);
        }
    }
}


