//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Events;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

    /// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
    [CreateAssetMenu(fileName = "SOEvent_string_string", menuName = "UKnack/SOEvents/SOEvent_string_string")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEvent_Concrete_string_string : SOEvent<string,string>
    {
        [SerializeField] private UnityEvent<string,string> _beforeSubscribers;
        [SerializeField] private UnityEvent<string,string> _afterSubscribers;

        internal override void InternalInvoke(string s1,string s2)
        {
            _beforeSubscribers.Invoke(s1,s2);
            base.InternalInvoke(s1,s2);
            _afterSubscribers.Invoke(s1,s2);
        }
    }
}


