//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Events;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

    /// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
    [CreateAssetMenu(fileName = "SOEvent_int", menuName = "UKnack/SOEvents/SOEvent_int")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEvent_Concrete_int : SOEvent<int>
    {
        [SerializeField] private UnityEvent<int> _beforeSubscribers;
        [SerializeField] private UnityEvent<int> _afterSubscribers;

        internal override void InternalInvoke(int t)
        {
            _beforeSubscribers.Invoke(t);
            base.InternalInvoke(t);
            _afterSubscribers.Invoke(t);
        }
    }
}


