//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Events;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

    /// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
    [CreateAssetMenu(fileName = "SOEvent_CallbackContext", menuName = "UKnack/SOEvents/SOEvent_CallbackContext")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEvent_Concrete_CallbackContext : SOEvent<CallbackContext>
    {
        [SerializeField] private UnityEvent<CallbackContext> _beforeSubscribers;
        [SerializeField] private UnityEvent<CallbackContext> _afterSubscribers;

        internal override void InternalInvoke(CallbackContext ctx)
        {
            _beforeSubscribers.Invoke(ctx);
            base.InternalInvoke(ctx);
            _afterSubscribers.Invoke(ctx);
        }
    }
}


