//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Events;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

    /// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
    [CreateAssetMenu(fileName = "SOEvent_float", menuName = "UKnack/SOEvents/SOEvent_float")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEvent_Concrete_float : SOEvent<float>
    {
        [SerializeField] private UnityEvent<float> _beforeSubscribers;
        [SerializeField] private UnityEvent<float> _afterSubscribers;

        internal override void InternalInvoke(float t)
        {
            _beforeSubscribers.Invoke(t);
            base.InternalInvoke(t);
            _afterSubscribers.Invoke(t);
        }
    }
}


