//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Concrete.Values;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

/// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
[CreateAssetMenu(fileName = "PublisherToSOEvent_CallbackContext", menuName = "UKnack/Publishers/To CallbackContext")]
[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
internal class SOPublisher_Concrete_CallbackContext : SOPublisher<CallbackContext>
{
    [SerializeField]
    [ValidReference(typeof(IEvent<CallbackContext>), nameof(IEvent<CallbackContext>.Validate),
        typeof(SOEvent<CallbackContext>),
        typeof(SOEvent_Concrete_CallbackContext)
    )] private SOEvent<CallbackContext> where;

    public override void Publish(CallbackContext ctx)
    {
        ValidateWhere();
        where.InternalInvoke(ctx);
    }

    internal void ValidateWhere() =>
        IEvent<CallbackContext>.Validate(where);

}

}

