//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Concrete.Values;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

/// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
[CreateAssetMenu(fileName = "PublisherToSOEvent_object", menuName = "UKnack/Publishers/To object")]
[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
public class SOPublisher_Concrete_object : SOPublisher<object>
{
    [SerializeField]
    [ValidReference(typeof(IEvent<object>), nameof(IEvent<object>.Validate),
        typeof(SOEvent<object>),
        typeof(SOEvent_Concrete_object)
        , typeof(SOValueMutable_Concrete_object)
    )] private SOEvent<object> where;

    public override void Publish(object obj)
    {
        ValidateWhere();
        where.InternalInvoke(obj);
    }

    internal void ValidateWhere() =>
        IEvent<object>.Validate(where);

}

}

