//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Concrete.Values;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

/// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
[CreateAssetMenu(fileName = "PublisherToSOEvent_int", menuName = "UKnack/Publishers/To int")]
[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
internal class SOPublisher_Concrete_int : SOPublisher<int>
{
    [SerializeField]
    [ValidReference(typeof(IEvent<int>), nameof(IEvent<int>.Validate),
        typeof(SOEvent<int>),
        typeof(SOEvent_Concrete_int)
        , typeof(SOValueMutable_Concrete_int)
    )] private SOEvent<int> where;

    public override void Publish(int t)
    {
        ValidateWhere();
        where.InternalInvoke(t);
    }

    internal void ValidateWhere() =>
        IEvent<int>.Validate(where);

}

}

