//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Concrete.Values;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

/// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
[CreateAssetMenu(fileName = "PublisherToSOEvent_float", menuName = "UKnack/Publishers/To float")]
[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
internal class SOPublisher_Concrete_float : SOPublisher<float>
{
    [SerializeField]
    [ValidReference(typeof(IEvent<float>), nameof(IEvent<float>.Validate),
        typeof(SOEvent<float>),
        typeof(SOEvent_Concrete_float)
        , typeof(SOValueMutable_Concrete_float)
    )] private SOEvent<float> where;

    public override void Publish(float t)
    {
        ValidateWhere();
        where.InternalInvoke(t);
    }

    internal void ValidateWhere() =>
        IEvent<float>.Validate(where);

}

}

