//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Concrete.Values;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

/// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
[CreateAssetMenu(fileName = "PublisherToSOEvent_string", menuName = "UKnack/Publishers/To string")]
[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
internal class SOPublisher_Concrete_string : SOPublisher<string>
{
    [SerializeField]
    [ValidReference(typeof(IEvent<string>), nameof(IEvent<string>.Validate),
        typeof(SOEvent<string>),
        typeof(SOEvent_Concrete_string)
        , typeof(SOValueMutable_Concrete_string)
    )] private SOEvent<string> where;

    public override void Publish(string s)
    {
        ValidateWhere();
        where.InternalInvoke(s);
    }

    internal void ValidateWhere() =>
        IEvent<string>.Validate(where);

}

}

