//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Concrete.Values;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

/// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
[CreateAssetMenu(fileName = "PublisherToSOEvent_object_object", menuName = "UKnack/Publishers/To object_object")]
[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
public class SOPublisher_Concrete_object_object : SOPublisher<object,object>
{
    [SerializeField]
    [ValidReference(typeof(IEvent<object,object>), nameof(IEvent<object,object>.Validate),
        typeof(SOEvent<object,object>),
        typeof(SOEvent_Concrete_object_object)
    )] private SOEvent<object,object> where;

    public override void Publish(object obj1,object obj2)
    {
        ValidateWhere();
        where.InternalInvoke(obj1,obj2);
    }

    internal void ValidateWhere() =>
        IEvent<object,object>.Validate(where);

}

}

