//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Concrete.Values;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

/// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
[CreateAssetMenu(fileName = "PublisherToSOEvent_string_string", menuName = "UKnack/Publishers/To string_string")]
[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
internal class SOPublisher_Concrete_string_string : SOPublisher<string,string>
{
    [SerializeField]
    [ValidReference(typeof(IEvent<string,string>), nameof(IEvent<string,string>.Validate),
        typeof(SOEvent<string,string>),
        typeof(SOEvent_Concrete_string_string)
    )] private SOEvent<string,string> where;

    public override void Publish(string s1,string s2)
    {
        ValidateWhere();
        where.InternalInvoke(s1,s2);
    }

    internal void ValidateWhere() =>
        IEvent<string,string>.Validate(where);

}

}

