//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Preconcrete_SOEventToUnityEventAdapter
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
    
using System;
using UnityEngine;
using UnityEngine.Events;
using UKnack.Attributes;
using UKnack.Events;

namespace UKnack.Preconcrete.Events
{

public abstract class SOEventToUnityEventAdapter<T1,T2,T3> : MonoBehaviour
{
    [SerializeField]
    protected UnityEvent<T1,T2,T3> _unityEvent;

    protected abstract IEvent<T1,T2,T3> _iEvent { get; }
    
    protected void OnEnable()
    {
        if (_unityEvent == null)
            throw new ArgumentNullException(nameof(_unityEvent));
            
        _iEvent.Subscribe(_unityEvent);
    }

    protected void OnDisable()
    {
        if (_unityEvent == null)
            throw new ArgumentNullException(nameof(_unityEvent));
            
        _iEvent.UnsubscribeNullSafe(_unityEvent);
    }
}

}
