//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from IValueGenerators
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Common;
using UKnack.Events;

namespace UKnack.KeyValues;

public partial interface IKeyValue<TKey, TValue> : IEvent<TKey, TValue>, IKeyValueGetter<TKey, TValue>
{
    public new static IKeyValue<TKey, TValue> Validate(UnityEngine.Object obj) =>
        CommonStatic.ValidCast<IKeyValue<TKey, TValue>>(obj);
}


