//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from IValueGenerators
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Common;

namespace UKnack.KeyValues;

public partial interface IKeyValueMutable<TKey, TValue> : IKeyValue<TKey, TValue>, IKeyValueSetter<TKey, TValue>
{
    public new static IKeyValueMutable<TKey, TValue> Validate(UnityEngine.Object obj) =>
        CommonStatic.ValidCast<IKeyValueMutable<TKey, TValue>>(obj);
}

