//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from IValueGenerators
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Common;

namespace UKnack.KeyValues;

public interface IKeyValueGetter<TKey, TValue>
{
    public TValue GetValue(TKey key);

    public static IKeyValueGetter<TKey, TValue> Validate(UnityEngine.Object obj) =>
        CommonStatic.ValidCast<IKeyValueGetter<TKey, TValue>>(obj);
}


