//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from IValueGenerators
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Common;

namespace UKnack.KeyValues;

public interface IKeyValueSetterWithoutNotification<TKey, TValue>
{
    void SetValueWithoutNotify(TKey key, TValue value);
}


