//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from IValueGenerators
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Common;

namespace UKnack.KeyValues;

public interface IKeyValueSetter<TKey, TValue>
{
    public void SetValue(TKey key, TValue value);

    public static IKeyValueSetter<TKey, TValue> Validate(UnityEngine.Object obj) => 
        CommonStatic.ValidCast<IKeyValueSetter<TKey, TValue>>(obj);

}


