//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from EventInterfaces
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using System;
using UKnack.Common;
using UnityEngine.Events;

namespace UKnack.Events;

public static partial class IEventUnSubscribeNullSafeExtension
{
    public static void UnsubscribeNullSafe(this IEvent ev, Action subscriber)
        { if (ev != null) ev.Unsubscribe(subscriber); }
    public static void UnsubscribeNullSafe(this IEvent ev, UnityEvent subscriber)
        { if (ev != null) ev.Unsubscribe(subscriber); }
    public static void UnsubscribeNullSafe(this IEvent ev, ISubscriberToEvent subscriber)
        { if (ev != null) ev.Unsubscribe(subscriber); }
}
public interface IEvent
{
    public static IEvent Validate(UnityEngine.Object obj) =>
        CommonStatic.ValidCast<IEvent>(obj);

    /// <summary>
    /// Subscribes reciever of event
    /// </summary>
    /// <param name="subscriber">To unsubscribe use UnsubscribeNullSafe extension method.
    /// subscriber will be called when something is published to event</param>
    public void Subscribe(Action subscriber);
    internal void Unsubscribe(Action subscriber);

    /// <summary>
    /// Subscribes reciever of event
    /// </summary>
    /// <param name="subscriber">To unsubscribe use UnsubscribeNullSafe extension method.
    /// subscriber will be called when something is published to event</param>
    public void Subscribe(UnityEvent subscriber);
    internal void Unsubscribe(UnityEvent subscriber);

    /// <summary>
    /// Subscribes reciever of event
    /// </summary>
    /// <param name="subscriber">To unsubscribe use UnsubscribeNullSafe extension method.
    /// subscriber will be called when something is published to event</param>
    public void Subscribe(ISubscriberToEvent subscriber);
    internal void Unsubscribe(ISubscriberToEvent subscriber);

}

