//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from EventInterfaces
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
    
using UKnack.Common;

namespace UKnack.Events;

public interface IPublisher 
{
    void Publish();

    public static IPublisher Validate(UnityEngine.Object obj) => 
        CommonStatic.ValidCast<IPublisher>(obj);
}

