//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from EventInterfaces
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Common;

namespace UKnack.Events;

public interface ISubscriberToEvent<T> : IHaveDescription
{
    public void OnEventNotification(T t);
    // public string Description { get; }
}
