//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from EventInterfaces
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UKnack.Common;

namespace UKnack.Events;

public interface ISubscriberToEvent : IHaveDescription
{
    public void OnEventNotification();
    // public string Description { get; }
}
