//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from EventScriptableObject
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
    
using System;
using UnityEngine;
using UKnack.Values;
using UKnack.Common;

namespace UKnack.Events;

public abstract class SOPublisher<T> : ScriptableObjectWithReadOnlyName, IPublisher<T>, IValueSetter<T>
{  
    public abstract void Publish(T t);

    //protected abstract SOEvent<T> GetEvent();
    //public virtual void Publish(T t) =>
    //    //internalEvent.InternalInvokeOnlyForPublisher(t);
    //    GetEvent().InternalInvoke(t);

    public void SetValue(T value) => Publish(value);
}

