//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from EventScriptableObject
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
    
using System;
using UnityEngine;
using UKnack.Values;
using UKnack.Common;

namespace UKnack.Events;

public abstract class SOPublisher : ScriptableObjectWithReadOnlyName, IPublisher
{  
    public abstract void Publish();

    //protected abstract SOEvent GetEvent();
    //public virtual void Publish() =>
    //    //internalEvent.InternalInvokeOnlyForPublisher();
    //    GetEvent().InternalInvoke();
}

