

// this file was generated as byproduct of generating *.gen.cs files from master template: Concrete_SOEventS
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_nongeneric.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_nongeneric.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_nongeneric.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_string.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_string.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_string.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_object.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_object.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_object.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_int.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_int.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_int.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_float.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_float.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_float.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_bool.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_bool.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_bool.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_Vector2.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_Vector2.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_Vector2.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_Vector3.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_Vector3.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_Vector3.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_string_string.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_string_string.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_string_string.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_object_object.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_object_object.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_object_object.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_CallbackContext.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_CallbackContext.cs
//// Generating: ../../UKnackBasisConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_CallbackContext.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_byte.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_byte.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_byte.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_short.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_short.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_short.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_long.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_long.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_long.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_Vector2Int.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_Vector2Int.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_Vector2Int.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOEvent_Concrete_Vector3Int.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOConditionalPublisher_Concrete_Vector3Int.cs
//// Generating: ../../UKnackProConcrete/Concrete/Events/_GeneratedSO_/SOPublisher_Concrete_Vector3Int.cs
