[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UKnackBasisConcrete")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UKnackPro")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UKnackProConcrete")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UserAssemblyFriendOfUKnack")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UserAssemblyFriendOfUKnackConcrete")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UKnackTests")]