//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Preconcrete_USetOrDefault
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using System;
using UnityEngine;
using UKnack.Values;
using UKnack.Attributes;

namespace UKnack.Preconcrete.Values;

/// <summary>
/// This struct intended to be used with scriptable objects
/// </summary>
[Serializable]
public struct USetOrPrefsOrDefault<T> : IValueGetter<T>, IValueSetter<T>  where T: IEquatable<T> //, ISerializationCallbackReceiver
{
    [SerializeField]
    [Tooltip("Value that will be default on every game start(Serialization)")]
    [DisableEditingInPlaymode]
    private T _defaultValue;
    [NonSerialized] private bool _isSet;
    [NonSerialized] private T _value;
    [SerializeField]
    [Tooltip("if this property empty, whitespaces or null, then no pref will be stored or loaded. \n")]
    [DisableEditingInPlaymode]
    private string _prefsKeyName;
    [SerializeField]
    [Tooltip("This value is for debug only purposes, to watch last value that was get")]
    private ValueDebugInfo<T> _debugLastValueGet;

    [SerializeField]
    [Tooltip("This value is for debug only purposes, to watch last value that was set")]
    private ValueDebugInfo<T> _debugLastValueSet;

    public T Value { get => GetValue(); set => SetValue(value); }
    public T GetValue() =>
        _debugLastValueGet.SetAndReturn( 
            _isSet ? _value :  GetPlayerPrefsOrDefault()  
            );

    public void SetValue(T value)
    {
        _isSet = true;
        if (value.Equals(_value) == false)
        {
            if (string.IsNullOrEmpty(_prefsKeyName) == false)
                Prefs.Loader.SetPref(_prefsKeyName, value);
        }
        _value = _debugLastValueSet.SetAndReturn( value );
        //SetLastValue();
    }

    private T GetPlayerPrefsOrDefault()
    {
        try
        {
            if (string.IsNullOrWhiteSpace(_prefsKeyName))
                _value = _defaultValue;
            else
                _value = (T)Prefs.Loader.GetPref(_prefsKeyName, typeof(T));
        }
        catch
        {
            _value = _defaultValue;
        }
        _isSet = true;
        return _value;
    }
 

    /*
    public void OnAfterDeserialize() =>
        SetLastValue();

    public void OnBeforeSerialize() =>
        SetLastValue();

    private void SetLastValue()
    {
#if UNITY_EDITOR
        _lastValue_Readonly = GetValue();
#endif
    }
    */
}

