//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Create_Commands
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
namespace UKnack;

public interface ICommand 
{
    void Execute();
    public string Description { get; }
}


