//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Create_Commands
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Events;

namespace UKnack.Commands;

public abstract class CommandMonoBehaviour<T1,T2> : MonoBehaviour, ICommand<T1,T2>//, ISubscriberToEvent<T1,T2>
{
    public abstract void Execute(T1 t1,T2 t2);
    //public virtual void OnEventNotification(T1 t1,T2 t2) => 
    //    Execute(t1,t2);
    public virtual string Description => this.GetType().ToString();
}

    