//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Create_Commands
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Events;
using UKnack.Common;

namespace UKnack.Commands;

public abstract class CommandScriptableObject<T1,T2,T3> : ScriptableObjectWithReadOnlyName, ICommand<T1,T2,T3>//, ISubscriberToEvent<T1,T2,T3>
{
    public abstract void Execute(T1 t1,T2 t2,T3 t3);
    //public virtual void OnEventNotification(T1 t1,T2 t2,T3 t3) => 
    //    Execute(t1,t2,t3);
    public virtual string Description => this.GetType().ToString();
}

