//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Create_Commands
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Events;

namespace UKnack.Commands;

public abstract class CommandMonoBehaviour<T> : MonoBehaviour, ICommand<T>//, ISubscriberToEvent<T>
{
    public abstract void Execute(T t);
    //public virtual void OnEventNotification(T t) => 
    //    Execute(t);
    public virtual string Description => this.GetType().ToString();
}

    