//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Create_Commands
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UKnack.Common;

namespace UKnack;

public interface ICommand<T1,T2> : IHaveDescription
{
    void Execute(T1 t1,T2 t2);
    ///public string Description { get; } //inherited from IHaveDescription
}


