//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_KeyValueSO
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

    
using UKnack.Preconcrete.KeyValues;
using UnityEngine;

namespace UKnack.Concrete.KeyValues
{
    [CreateAssetMenu(fileName = "SOKeyValueMutable_int_string", menuName = "UKnack/SOKeyValueMutable/int_string_dictionary", order = 190)]
    internal sealed class SOKeyValueMutable_Concrete_int_string : SOKeyValueMutableDictionaryWithDefaultValue<int, string>
    {
    }
}


